const headersUsers = ["Nombre", "Correo electrónico", "Rol", "Acciones"],
  headersUsersSystem = ["Nombre", "Correo electrónico", "Rol", "Acciones"],
  headersEmpleados = [
    "",
    "ID",
    "Nombre",
    "Paterno",
    "Materno",
    "RFC",
    "CURP",
    "Extensión",
    "Correo",
    "Puesto",
    "Area",
  ],
  headersDispositivos = [
    "",
    "Nombre",
    "Paterno",
    "Materno",
    "Status",
    "Perfil",
    "Descripción",
    "NoSerie",
    "Marca",
    "Modelo",
    "Ip",
  ],
  headersDispositivosA = [
    "",
    "Status",
    "Perfil",
    "Descripción",
    "NoSerie",
    "Marca",
    "Modelo",
    "Ip",
  ],
  cabeceraEquipos = [
    "",
    "Nombre",
    "Paterno",
    "Materno",
    "Perfil",
    "Descripción",
    "Marca",
    "Modelo",
    "No. Serie",
    "Hostname",
    "Username",
    "IP",
    "Perfil",
    "Descripción",
    "Marca",
    "Modelo",
    "No. Serie",
  ],
  cabeceraComputadoras = [
    "",
    "Nombre",
    "Paterno",
    "Materno",
    "Perfil",
    "Descripción",
    "Marca",
    "Modelo",
    "No. Serie",
    "Hostname",
    "Username",
    "IP",
  ],
  cabeceraDispositivos = [
    "",
    "Nombre",
    "Paterno",
    "Materno",
    "Perfil",
    "Descripción",
    "Marca",
    "Modelo",
    "No. Serie",
    "IP",
  ],
  cabeceraPerifericos = [
    "",
    "Perfil",
    "Descripción",
    "Marca",
    "Modelo",
    "No. Serie",
    "Dispositivo Padre",
  ],
  cabeceraResguardos = [
    "",
    "#",
    "Nombre",
    "NoSerie",
    "URL",
    "Fecha del documento",
    "Fecha de última modificación",
  ],
  cabeceraHistorial = [
    "",
    "Acción",
    "Usuario",
    "Tabla",
    "Fecha",
    "ID Modificado",
    "ID Actual",
  ];

const tableHead = {
  headersUsers,
  headersUsersSystem,
  headersEmpleados,
  headersDispositivos,
  headersDispositivosA,
  cabeceraEquipos,
  cabeceraComputadoras,
  cabeceraPerifericos,
  cabeceraDispositivos,
  cabeceraResguardos,
  cabeceraHistorial,
};

export default tableHead;
